/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

export const CREATE_CAR_PARK = "CREATE_CAR_PARK";
export const CREATE_CAR_PARK_SUCCESS = "CREATE_CAR_PARK_SUCCESS";

export const GET_CAR_PARK_LIST = "GET_CAR_PARK_LIST";
export const GET_CAR_PARK_LIST_SUCCESS = "GET_CAR_PARK_LIST_SUCCESS";
export const CAR_PARK_DELETE = "CAR_PARK_DELETE";
export const CAR_PARK_DELETE_SUCCESS = "CAR_PARK_DELETE_SUCCESS";
export const CAR_PARK_EDIT = "CAR_PARK_EDIT";
export const CAR_PARK_EDIT_SUCCESS = "CAR_PARK_EDIT_SUCCESS";

export const GET_COMPANY_LIST = "GET_COMPANY_LIST";
export const GET_COMPANY_LIST_SUCCESS = "GET_COMPANY_LIST_SUCCESS";

export const GET_CAR_PARK = "GET_CAR_PARK";
export const GET_CAR_PARK_SUCCESS = "GET_CAR_PARK_SUCCESS";

export * from "./menu/actions";
export * from "./settings/actions";
export * from "./car-park/actions";
export * from './auth/actions';
export * from './company/actions';